[env:esp32dev]
platform  = espressif32
board     = esp32dev
framework = arduino
monitor_speed = 115200
build_type = debug
monitor_filters = esp32_exception_decoder
board_build.partitions     = huge_app.csv
board_build.flash_mode     = qio
board_build.flash_frequency = 80000000

lib_deps =
    bodmer/TFT_eSPI @ ^2.5.43
    https://github.com/PaulStoffregen/XPT2046_Touchscreen.git
    lvgl/lvgl @ ^9.2.0

build_flags =
    -D USER_SETUP_LOADED=1
    -include src/User_Setup.h
    -D LV_CONF_INCLUDE_SIMPLE
    -include src/lv_conf.h
    -D LV_USE_TFT_ESPI=1
    -O2
    -mfix-esp32-psram-cache-issue
    -mlongcalls
